### ISSUE TITLE
active_admin_logged_out layout not up to date

### ISSUE THREAD

**Issue by WiechersV** [cle61/arctic_admin#16]
Hi, @cle61 !

First of all, thanks for the amazing theme, I really liked it!
I'm trying to use it on my current project and in development, it works fine. However, in production, it throws an `undefined method` error.

Digging around, I found what is the problem:
6 months ago, `activeadmin` got updated and they changed how they add styles to this page ([Commit for reference](https://github.com/activeadmin/activeadmin/commit/61502c2900c66b70805be70654c1c8f2ccc83399#diff-9743ec0aea52af96c32e367c553ae75a))
`arctic_admin` still uses it's old syntax, that's why the error is thrown (Though I'm having a hard time imagining why it's thrown only in production... Maybe rails getting old `activeadmin` records from previous projects as a fallback? Anyways...)

Just wanted to report this issue! Let me know if you need any help, want me to send a PR or even if updating it it's not in your plans at all

Cheers (:

**Comment by cle61** [comment]
Hmm ok got it, i thinks it's because you use the `master` branch for activeadmin but they have release a [gem version](https://rubygems.org/gems/activeadmin/versions/0.6.6) who use the old style.
I will make a patch to handle the layout depending on version

**Comment by kensk8** [comment]
Hi, like @WiechersV said is a great teme i used on a previous project and it was amazing, but now i start a new project with all update gems, and  i got the same problem i think, this only happens on production too, I put my log if help you:

`I, [2017-10-25T12:50:06.049036 #23155]  INFO -- : [0cbf7032-00d6-4305-beba-ce8c89567df4] Started GET "/admin/login" for 190.162.109.122 at 2017-10-25 12:50:06 +0000
I, [2017-10-25T12:50:06.049832 #23155]  INFO -- : [0cbf7032-00d6-4305-beba-ce8c89567df4] Processing by ActiveAdmin::Devise::SessionsController#new as HTML
I, [2017-10-25T12:50:06.051012 #23155]  INFO -- : [0cbf7032-00d6-4305-beba-ce8c89567df4]   Rendering /home/deploy/merck-origin/shared/bundle/ruby/2.4.0/bundler/gems/activeadmin-95b8276d307a/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out
I, [2017-10-25T12:50:06.055606 #23155]  INFO -- : [0cbf7032-00d6-4305-beba-ce8c89567df4]   Rendered /home/deploy/merck-origin/shared/bundle/ruby/2.4.0/bundler/gems/activeadmin-95b8276d307a/app/views/active_admin/devise/shared/_links.erb (0.2ms)
I, [2017-10-25T12:50:06.055783 #23155]  INFO -- : [0cbf7032-00d6-4305-beba-ce8c89567df4]   Rendered /home/deploy/merck-origin/shared/bundle/ruby/2.4.0/bundler/gems/activeadmin-95b8276d307a/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (4.6ms)
I, [2017-10-25T12:50:06.062885 #23155]  INFO -- : [0cbf7032-00d6-4305-beba-ce8c89567df4] Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.0ms)
F, [2017-10-25T12:50:06.064219 #23155] FATAL -- : [0cbf7032-00d6-4305-beba-ce8c89567df4]
F, [2017-10-25T12:50:06.064341 #23155] FATAL -- : [0cbf7032-00d6-4305-beba-ce8c89567df4] ActionView::Template::Error (undefined method `stylesheets' for #<ActiveAdmin::Application:0x00000004065898>):
F, [2017-10-25T12:50:06.064531 #23155] FATAL -- : [0cbf7032-00d6-4305-beba-ce8c89567df4]      6:
[0cbf7032-00d6-4305-beba-ce8c89567df4]      7:   <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>
[0cbf7032-00d6-4305-beba-ce8c89567df4]      8:
[0cbf7032-00d6-4305-beba-ce8c89567df4]      9:   <% ActiveAdmin.application.stylesheets.each do |style, options| %>
[0cbf7032-00d6-4305-beba-ce8c89567df4]     10:     <%= stylesheet_link_tag style, options %>
[0cbf7032-00d6-4305-beba-ce8c89567df4]     11:   <% end %>
[0cbf7032-00d6-4305-beba-ce8c89567df4]     12:   <% ActiveAdmin.application.javascripts.each do |path| %>
F, [2017-10-25T12:50:06.064639 #23155] FATAL -- : [0cbf7032-00d6-4305-beba-ce8c89567df4]
F, [2017-10-25T12:50:06.064733 #23155] FATAL -- : [0cbf7032-00d6-4305-beba-ce8c89567df4] /home/deploy/merck-origin/shared/bundle/ruby/2.4.0/bundler/gems/activeadmin-95b8276d307a/lib/active_admin/application.rb:37:in `method_missing'
[0cbf7032-00d6-4305-beba-ce8c89567df4] arctic_admin (1.3.0) app/views/layouts/active_admin_logged_out.html.erb:9:in `__home_deploy_merck_origin_shared_bundle_ruby_______gems_arctic_admin_______app_views_layouts_active_admin_logged_out_html_erb__3218813297212775495_70020416665780'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/template.rb:157:in `block in render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/notifications.rb:168:in `instrument'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/template.rb:352:in `instrument_render_template'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/template.rb:155:in `render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:14:in `render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/renderer/renderer.rb:42:in `render_template'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/renderer/renderer.rb:23:in `render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/rendering.rb:103:in `_render_template'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/streaming.rb:217:in `_render_template'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/rendering.rb:83:in `render_to_body'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/abstract_controller/rendering.rb:24:in `render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/rendering.rb:36:in `render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[0cbf7032-00d6-4305-beba-ce8c89567df4] /home/deploy/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] responders (2.4.0) lib/action_controller/responder.rb:238:in `default_render'
[0cbf7032-00d6-4305-beba-ce8c89567df4] responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
[0cbf7032-00d6-4305-beba-ce8c89567df4] responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
[0cbf7032-00d6-4305-beba-ce8c89567df4] responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
[0cbf7032-00d6-4305-beba-ce8c89567df4] devise (4.3.0) app/controllers/devise/sessions_controller.rb:12:in `new'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[0cbf7032-00d6-4305-beba-ce8c89567df4] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/etag.rb:25:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/head.rb:12:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
[0cbf7032-00d6-4305-beba-ce8c89567df4] railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[0cbf7032-00d6-4305-beba-ce8c89567df4] railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] railties (5.1.4) lib/rails/engine.rb:522:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] puma (3.10.0) lib/puma/configuration.rb:225:in `call'
[0cbf7032-00d6-4305-beba-ce8c89567df4] puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
[0cbf7032-00d6-4305-beba-ce8c89567df4] puma (3.10.0) lib/puma/server.rb:437:in `process_client'
[0cbf7032-00d6-4305-beba-ce8c89567df4] puma (3.10.0) lib/puma/server.rb:301:in `block in run'
[0cbf7032-00d6-4305-beba-ce8c89567df4] puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
I, [2017-10-25T12:50:29.298290 #23155]  INFO -- : [3faebc13-bd86-4ef3-a86d-24bd31efadf2] Started GET "/.well-known/acme-challenge/Qr0iSrrWaJG5KfSmie4ZyW3G-es60Go06r34vO2HLYk" for 190.163.220.21 at 2017-10-25 12:50:29 +0000
F, [2017-10-25T12:50:29.299051 #23155] FATAL -- : [3faebc13-bd86-4ef3-a86d-24bd31efadf2]
F, [2017-10-25T12:50:29.299220 #23155] FATAL -- : [3faebc13-bd86-4ef3-a86d-24bd31efadf2] ActionController::RoutingError (No route matches [GET] "/.well-known/acme-challenge/Qr0iSrrWaJG5KfSmie4ZyW3G-es60Go06r34vO2HLYk"):
F, [2017-10-25T12:50:29.299328 #23155] FATAL -- : [3faebc13-bd86-4ef3-a86d-24bd31efadf2]
F, [2017-10-25T12:50:29.299443 #23155] FATAL -- : [3faebc13-bd86-4ef3-a86d-24bd31efadf2] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] railties (5.1.4) lib/rails/engine.rb:522:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] puma (3.10.0) lib/puma/configuration.rb:225:in `call'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] puma (3.10.0) lib/puma/server.rb:437:in `process_client'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] puma (3.10.0) lib/puma/server.rb:301:in `block in run'
[3faebc13-bd86-4ef3-a86d-24bd31efadf2] puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
I, [2017-10-25T12:51:53.373117 #23155]  INFO -- : [d6639fc7-3086-4efd-bfb4-dbff4a47d2d6] Started GET "/" for 190.162.109.122 at 2017-10-25 12:51:53 +0000
I, [2017-10-25T12:51:53.374399 #23155]  INFO -- : [d6639fc7-3086-4efd-bfb4-dbff4a47d2d6] Processing by WelcomeController#index as HTML
I, [2017-10-25T12:51:53.377885 #23155]  INFO -- : [d6639fc7-3086-4efd-bfb4-dbff4a47d2d6]   Rendering welcome/index.html.erb within layouts/application
I, [2017-10-25T12:51:53.378406 #23155]  INFO -- : [d6639fc7-3086-4efd-bfb4-dbff4a47d2d6]   Rendered welcome/index.html.erb within layouts/application (0.4ms)
I, [2017-10-25T12:51:53.379897 #23155]  INFO -- : [d6639fc7-3086-4efd-bfb4-dbff4a47d2d6] Completed 200 OK in 5ms (Views: 4.4ms | ActiveRecord: 0.0ms)
I, [2017-10-25T12:51:55.368450 #23155]  INFO -- : [50190c7f-1d14-4378-93b3-42bee9f9a544] Started GET "/.well-known/acme-challenge/Qr0iSrrWaJG5KfSmie4ZyW3G-es60Go06r34vO2HLYk" for 190.162.109.122 at 2017-10-25 12:51:55 +0000
F, [2017-10-25T12:51:55.369153 #23155] FATAL -- : [50190c7f-1d14-4378-93b3-42bee9f9a544]
F, [2017-10-25T12:51:55.369336 #23155] FATAL -- : [50190c7f-1d14-4378-93b3-42bee9f9a544] ActionController::RoutingError (No route matches [GET] "/.well-known/acme-challenge/Qr0iSrrWaJG5KfSmie4ZyW3G-es60Go06r34vO2HLYk"):
F, [2017-10-25T12:51:55.369458 #23155] FATAL -- : [50190c7f-1d14-4378-93b3-42bee9f9a544]
F, [2017-10-25T12:51:55.369573 #23155] FATAL -- : [50190c7f-1d14-4378-93b3-42bee9f9a544] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
[50190c7f-1d14-4378-93b3-42bee9f9a544] railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[50190c7f-1d14-4378-93b3-42bee9f9a544] activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[50190c7f-1d14-4378-93b3-42bee9f9a544] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[50190c7f-1d14-4378-93b3-42bee9f9a544] railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] railties (5.1.4) lib/rails/engine.rb:522:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] puma (3.10.0) lib/puma/configuration.rb:225:in `call'
[50190c7f-1d14-4378-93b3-42bee9f9a544] puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
[50190c7f-1d14-4378-93b3-42bee9f9a544] puma (3.10.0) lib/puma/server.rb:437:in `process_client'
[50190c7f-1d14-4378-93b3-42bee9f9a544] puma (3.10.0) lib/puma/server.rb:301:in `block in run'
[50190c7f-1d14-4378-93b3-42bee9f9a544] puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

**Comment by cle61** [comment]
Hi,

can you test with the branch `2-0-alpha` like this :

```ruby
gem 'arctic_admin', github: 'activeadmin/activeadmin', branch: '2-0-alpha'
```

thanks
